version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: codimd_mariadb
    restart: always
    volumes:
      - /docker/codimd:/config
    environment:
      - MYSQL_ROOT_PASSWORD=leonsec
      - MYSQL_DATABASE=codimd
      - MYSQL_USER=codimd
      - MYSQL_PASSWORD=leonsec
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Shanghai
  codimd:
    image: linuxserver/codimd:latest
    container_name: codimd
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /docker/codimd:/config
    environment:
      - DB_HOST=mariadb
      - DB_USER=codimd
      - DB_PASS=leonsec
      - DB_NAME=codimd
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Shanghai
    ports:
      - "3000:3000"
